/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
  },
  exchangeRates: {
    ExchangeRates: () => import('#controllers/exchange_rates/exchange_rates_controller'),
  },
  journalisations: {
    Journalisations: () => import('#controllers/journalisations/journalisations_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
}
