/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CashSessionSchema extends BaseModel {
  static $columns = ['closedAt', 'closingAmount', 'closingCurrency', 'createdAt', 'id', 'openedAt', 'openingAmount', 'openingCurrency', 'status', 'updatedAt', 'userId'] as const
  $columns = CashSessionSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare closingAmount: string | null
  @column()
  declare closingCurrency: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare openingAmount: string
  @column()
  declare openingCurrency: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'customerType', 'email', 'fullName', 'id', 'isActive', 'phoneNumber', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerType: string
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare phoneNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExchangeRateSchema extends BaseModel {
  static $columns = ['createdAt', 'exchangeRate', 'id', 'sellRate', 'updatedAt'] as const
  $columns = ExchangeRateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare exchangeRate: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sellRate: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JournalisationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'module', 'updatedAt', 'userId'] as const
  $columns = JournalisationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column()
  declare module: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductServiceSchema extends BaseModel {
  static $columns = ['baseUnit', 'categoryId', 'createdAt', 'id', 'isActive', 'name', 'packagingCapacity', 'packagingUnit', 'priceCdf', 'priceUsd', 'type', 'updatedAt'] as const
  $columns = ProductServiceSchema.$columns
  @column()
  declare baseUnit: string
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare packagingCapacity: number | null
  @column()
  declare packagingUnit: string | null
  @column()
  declare priceCdf: string
  @column()
  declare priceUsd: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'entries', 'id', 'initialStock', 'losses', 'observation', 'outputs', 'physicalStock', 'productId', 'updatedAt'] as const
  $columns = StockMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare entries: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare initialStock: string
  @column()
  declare losses: string | null
  @column()
  declare observation: string | null
  @column()
  declare outputs: string
  @column()
  declare physicalStock: string | null
  @column()
  declare productId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'failedLoginAttempts', 'fullName', 'id', 'password', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare failedLoginAttempts: number
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
