/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type CashSessionTransformer from '#transformers/cash_session_transformer'
import type CustomerTransformer from '#transformers/customer_transformer'
import type ExchangeRateTransformer from '#transformers/exchange_rate_transformer'
import type JournalisationTransformer from '#transformers/journalisation_transformer'
import type ProductCategoryTransformer from '#transformers/product_category_transformer'
import type ProductServiceTransformer from '#transformers/product_service_transformer'
import type SaleItemTransformer from '#transformers/sale_item_transformer'
import type SaleRecoveryTransformer from '#transformers/sale_recovery_transformer'
import type SaleTransformer from '#transformers/sale_transformer'
import type StockMovementTransformer from '#transformers/stock_movement_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type DebtTransformer from '#transformers/debt_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type CashSession = InferData<CashSessionTransformer>
  export namespace CashSession {
    export type Variants = InferVariants<CashSessionTransformer>
  }
  export type Customer = InferData<CustomerTransformer>
  export namespace Customer {
    export type Variants = InferVariants<CustomerTransformer>
  }
  export type ExchangeRate = InferData<ExchangeRateTransformer>
  export namespace ExchangeRate {
    export type Variants = InferVariants<ExchangeRateTransformer>
  }
  export type Journalisation = InferData<JournalisationTransformer>
  export namespace Journalisation {
    export type Variants = InferVariants<JournalisationTransformer>
  }
  export type ProductCategory = InferData<ProductCategoryTransformer>
  export namespace ProductCategory {
    export type Variants = InferVariants<ProductCategoryTransformer>
  }
  export type ProductService = InferData<ProductServiceTransformer>
  export namespace ProductService {
    export type Variants = InferVariants<ProductServiceTransformer>
  }
  export type SaleItem = InferData<SaleItemTransformer>
  export namespace SaleItem {
    export type Variants = InferVariants<SaleItemTransformer>
  }
  export type SaleRecovery = InferData<SaleRecoveryTransformer>
  export namespace SaleRecovery {
    export type Variants = InferVariants<SaleRecoveryTransformer>
  }
  export type Sale = InferData<SaleTransformer>
  export namespace Sale {
    export type Variants = InferVariants<SaleTransformer>
  }
  export type StockMovement = InferData<StockMovementTransformer>
  export namespace StockMovement {
    export type Variants = InferVariants<StockMovementTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Debt = InferData<DebtTransformer>
  export namespace Debt {
    export type Variants = InferVariants<DebtTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
